//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all open libraries in order to change the path..
        /// </summary>
        internal static string CloseLibrariesToChangePathMessage {
            get {
                return ResourceManager.GetString("CloseLibrariesToChangePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all open libraries in order to modify options..
        /// </summary>
        internal static string CloseLibrariesToModifyOptionsMessage {
            get {
                return ResourceManager.GetString("CloseLibrariesToModifyOptionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very poorly handled collectible with a heavy accumulation of major defects..
        /// </summary>
        internal static string FairDescription {
            get {
                return ResourceManager.GetString("FairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows extensive evidence of handling with a heavy accumulation of major defects..
        /// </summary>
        internal static string FairGoodDescription {
            get {
                return ResourceManager.GetString("FairGoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slightly above-average collectible with a major defect and some smaller defects, or a significant accumulation of small defects..
        /// </summary>
        internal static string FineDescription {
            get {
                return ResourceManager.GetString("FineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slightly above-average collectible with several moderate defects..
        /// </summary>
        internal static string FineMinusDescription {
            get {
                return ResourceManager.GetString("FineMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An above-average collectible with a major defect and some smaller defects, or a significant accumulation of small defects..
        /// </summary>
        internal static string FinePlusDescription {
            get {
                return ResourceManager.GetString("FinePlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An above-average collectible with a major defect or an accumulation of small defects..
        /// </summary>
        internal static string FineVeryFineDescription {
            get {
                return ResourceManager.GetString("FineVeryFineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest grade assigned. The collectible must have no evidence of any manufacturing or handling defects..
        /// </summary>
        internal static string GemMintDescription {
            get {
                return ResourceManager.GetString("GemMintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows extensive evidence of handling with numerous moderate-to-major defects..
        /// </summary>
        internal static string GoodDescription {
            get {
                return ResourceManager.GetString("GoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows extensive evidence of handling with numerous major defects..
        /// </summary>
        internal static string GoodMinusDescription {
            get {
                return ResourceManager.GetString("GoodMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows extensive evidence of handling with multiple moderate-to-major defects..
        /// </summary>
        internal static string GoodPlusDescription {
            get {
                return ResourceManager.GetString("GoodPlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows significant evidence of handling with several moderate-to-major defects..
        /// </summary>
        internal static string GoodVeryGoodDescription {
            get {
                return ResourceManager.GetString("GoodVeryGoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg Image Files (*.jpg).
        /// </summary>
        internal static string JpegFiles {
            get {
                return ResourceManager.GetString("JpegFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collectible is nearly indistinguishable from a 10.0 but will have a very minor manufacturing defect. It will not have any evidence of handling defects..
        /// </summary>
        internal static string MintDescription {
            get {
                return ResourceManager.GetString("MintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to move all XML files to the new location?.
        /// </summary>
        internal static string MoveXMLFilesQuestion {
            get {
                return ResourceManager.GetString("MoveXMLFilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very well-preserved collectible with minor wear and small manufacturing or handling defects..
        /// </summary>
        internal static string NearMintDescription {
            get {
                return ResourceManager.GetString("NearMintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nearly perfect collectible with negligible handling or manufacturing defects..
        /// </summary>
        internal static string NearMintMintDescription {
            get {
                return ResourceManager.GetString("NearMintMintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very well-preserved collectible with some wear and small manufacturing or handling defects..
        /// </summary>
        internal static string NearMintMinusDescription {
            get {
                return ResourceManager.GetString("NearMintMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very well-preserved collectible with several minor manufacturing or handling defects..
        /// </summary>
        internal static string NearMintPlusDescription {
            get {
                return ResourceManager.GetString("NearMintPlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Network Graphics Files (*.png).
        /// </summary>
        internal static string PngFiles {
            get {
                return ResourceManager.GetString("PngFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A heavily defaced collectible with a number major defects. Some pieces will also be missing..
        /// </summary>
        internal static string PoorDescription {
            get {
                return ResourceManager.GetString("PoorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        internal static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really like to remove the selected comic?.
        /// </summary>
        internal static string RemoveComicQuestion {
            get {
                return ResourceManager.GetString("RemoveComicQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really like to remove the complete library? This cannot be undone..
        /// </summary>
        internal static string RemoveLibraryQuestion {
            get {
                return ResourceManager.GetString("RemoveLibraryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really like to remove the selected option? This cannot be undone and it will remove the property in all assigned comics..
        /// </summary>
        internal static string RemoveOptionQuestion {
            get {
                return ResourceManager.GetString("RemoveOptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the changes?.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder..
        /// </summary>
        internal static string SelectAFolderMessage {
            get {
                return ResourceManager.GetString("SelectAFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not rated yet..
        /// </summary>
        internal static string UnratedDescription {
            get {
                return ResourceManager.GetString("UnratedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attractive collectible with a moderate defect or an accumulation of small defects..
        /// </summary>
        internal static string VeryFineDescription {
            get {
                return ResourceManager.GetString("VeryFineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An above-average collectible with a moderate defect or an accumulation of small defects..
        /// </summary>
        internal static string VeryFineMinusDescription {
            get {
                return ResourceManager.GetString("VeryFineMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very well-preserved collectible with good eye appeal. There will be a number of minor handling and/or manufacturing defects..
        /// </summary>
        internal static string VeryFineNearMintDescription {
            get {
                return ResourceManager.GetString("VeryFineNearMintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attractive collectible with a moderate defect or a number of small defects..
        /// </summary>
        internal static string VeryFinePlusDescription {
            get {
                return ResourceManager.GetString("VeryFinePlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A below-average collectible with multiple moderate defects..
        /// </summary>
        internal static string VeryGoodDescription {
            get {
                return ResourceManager.GetString("VeryGoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An average collectible with several moderate defects..
        /// </summary>
        internal static string VeryGoodFineDescription {
            get {
                return ResourceManager.GetString("VeryGoodFineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A below-average collectible with several major defects or an accumulation of multiple moderate defects..
        /// </summary>
        internal static string VeryGoodMinusDescription {
            get {
                return ResourceManager.GetString("VeryGoodMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slightly below-average collectible with multiple moderate defects..
        /// </summary>
        internal static string VeryGoodPlusDescription {
            get {
                return ResourceManager.GetString("VeryGoodPlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
