//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comic.
        /// </summary>
        public static string AddComic {
            get {
                return ResourceManager.GetString("AddComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new comic..
        /// </summary>
        public static string AddComicTooltip {
            get {
                return ResourceManager.GetString("AddComicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Option.
        /// </summary>
        public static string AddOption {
            get {
                return ResourceManager.GetString("AddOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load file &apos;{0}&apos;..
        /// </summary>
        public static string CannotLoadFileMessage {
            get {
                return ResourceManager.GetString("CannotLoadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save file &apos;{0}&apos;..
        /// </summary>
        public static string CannotSaveFileMessage {
            get {
                return ResourceManager.GetString("CannotSaveFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image.
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all open libraries in order to change the path..
        /// </summary>
        public static string CloseLibrariesToChangePathMessage {
            get {
                return ResourceManager.GetString("CloseLibrariesToChangePathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all open libraries in order to modify options..
        /// </summary>
        public static string CloseLibrariesToModifyOptionsMessage {
            get {
                return ResourceManager.GetString("CloseLibrariesToModifyOptionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector&apos;s Edition.
        /// </summary>
        public static string CollectorsEdition {
            get {
                return ResourceManager.GetString("CollectorsEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic.
        /// </summary>
        public static string Comic {
            get {
                return ResourceManager.GetString("Comic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comics.
        /// </summary>
        public static string Comics {
            get {
                return ResourceManager.GetString("Comics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Library.
        /// </summary>
        public static string CurrentLibrary {
            get {
                return ResourceManager.GetString("CurrentLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Option.
        /// </summary>
        public static string EditOption {
            get {
                return ResourceManager.GetString("EditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of new library.
        /// </summary>
        public static string EnterNameOfLibrary {
            get {
                return ResourceManager.GetString("EnterNameOfLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Image.
        /// </summary>
        public static string ExportImage {
            get {
                return ResourceManager.GetString("ExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very poorly handled collectible with a heavy accumulation of major defects..
        /// </summary>
        public static string FairDescription {
            get {
                return ResourceManager.GetString("FairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows extensive evidence of handling with a heavy accumulation of major defects..
        /// </summary>
        public static string FairGoodDescription {
            get {
                return ResourceManager.GetString("FairGoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slightly above-average collectible with a major defect and some smaller defects, or a significant accumulation of small defects..
        /// </summary>
        public static string FineDescription {
            get {
                return ResourceManager.GetString("FineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slightly above-average collectible with several moderate defects..
        /// </summary>
        public static string FineMinusDescription {
            get {
                return ResourceManager.GetString("FineMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An above-average collectible with a major defect and some smaller defects, or a significant accumulation of small defects..
        /// </summary>
        public static string FinePlusDescription {
            get {
                return ResourceManager.GetString("FinePlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An above-average collectible with a major defect or an accumulation of small defects..
        /// </summary>
        public static string FineVeryFineDescription {
            get {
                return ResourceManager.GetString("FineVeryFineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest grade assigned. The collectible must have no evidence of any manufacturing or handling defects..
        /// </summary>
        public static string GemMintDescription {
            get {
                return ResourceManager.GetString("GemMintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows extensive evidence of handling with numerous moderate-to-major defects..
        /// </summary>
        public static string GoodDescription {
            get {
                return ResourceManager.GetString("GoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows extensive evidence of handling with numerous major defects..
        /// </summary>
        public static string GoodMinusDescription {
            get {
                return ResourceManager.GetString("GoodMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows extensive evidence of handling with multiple moderate-to-major defects..
        /// </summary>
        public static string GoodPlusDescription {
            get {
                return ResourceManager.GetString("GoodPlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collectible that shows significant evidence of handling with several moderate-to-major defects..
        /// </summary>
        public static string GoodVeryGoodDescription {
            get {
                return ResourceManager.GetString("GoodVeryGoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grading.
        /// </summary>
        public static string Grading {
            get {
                return ResourceManager.GetString("Grading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Number.
        /// </summary>
        public static string IssueNumber {
            get {
                return ResourceManager.GetString("IssueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg Image Files (*.jpg).
        /// </summary>
        public static string JpegFiles {
            get {
                return ResourceManager.GetString("JpegFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        public static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries Path.
        /// </summary>
        public static string LibrariesPath {
            get {
                return ResourceManager.GetString("LibrariesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Edition.
        /// </summary>
        public static string LimitedEdition {
            get {
                return ResourceManager.GetString("LimitedEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Libraries.
        /// </summary>
        public static string ManageLibraries {
            get {
                return ResourceManager.GetString("ManageLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the popup to manage the libraries..
        /// </summary>
        public static string ManageLibrariesTooltip {
            get {
                return ResourceManager.GetString("ManageLibrariesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collectible is nearly indistinguishable from a 10.0 but will have a very minor manufacturing defect. It will not have any evidence of handling defects..
        /// </summary>
        public static string MintDescription {
            get {
                return ResourceManager.GetString("MintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Library.
        /// </summary>
        public static string MoveToLibrary {
            get {
                return ResourceManager.GetString("MoveToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected comic into a different library..
        /// </summary>
        public static string MoveToLibraryTooltip {
            get {
                return ResourceManager.GetString("MoveToLibraryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to move all XML files to the new location?.
        /// </summary>
        public static string MoveXMLFilesQuestion {
            get {
                return ResourceManager.GetString("MoveXMLFilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very well-preserved collectible with minor wear and small manufacturing or handling defects..
        /// </summary>
        public static string NearMintDescription {
            get {
                return ResourceManager.GetString("NearMintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nearly perfect collectible with negligible handling or manufacturing defects..
        /// </summary>
        public static string NearMintMintDescription {
            get {
                return ResourceManager.GetString("NearMintMintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very well-preserved collectible with some wear and small manufacturing or handling defects..
        /// </summary>
        public static string NearMintMinusDescription {
            get {
                return ResourceManager.GetString("NearMintMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very well-preserved collectible with several minor manufacturing or handling defects..
        /// </summary>
        public static string NearMintPlusDescription {
            get {
                return ResourceManager.GetString("NearMintPlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Network Graphics Files (*.png).
        /// </summary>
        public static string PngFiles {
            get {
                return ResourceManager.GetString("PngFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A heavily defaced collectible with a number major defects. Some pieces will also be missing..
        /// </summary>
        public static string PoorDescription {
            get {
                return ResourceManager.GetString("PoorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Comic.
        /// </summary>
        public static string RemoveComic {
            get {
                return ResourceManager.GetString("RemoveComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really like to remove the selected comic?.
        /// </summary>
        public static string RemoveComicQuestion {
            get {
                return ResourceManager.GetString("RemoveComicQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected comic..
        /// </summary>
        public static string RemoveComicTooltip {
            get {
                return ResourceManager.GetString("RemoveComicTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Image.
        /// </summary>
        public static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Library.
        /// </summary>
        public static string RemoveLibrary {
            get {
                return ResourceManager.GetString("RemoveLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really like to remove the complete library? This cannot be undone..
        /// </summary>
        public static string RemoveLibraryQuestion {
            get {
                return ResourceManager.GetString("RemoveLibraryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Option.
        /// </summary>
        public static string RemoveOption {
            get {
                return ResourceManager.GetString("RemoveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really like to remove the selected option? This cannot be undone and it will remove the property in all assigned comics..
        /// </summary>
        public static string RemoveOptionQuestion {
            get {
                return ResourceManager.GetString("RemoveOptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the changes?.
        /// </summary>
        public static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Library.
        /// </summary>
        public static string SaveLibrary {
            get {
                return ResourceManager.GetString("SaveLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the current library..
        /// </summary>
        public static string SaveLibraryTooltip {
            get {
                return ResourceManager.GetString("SaveLibraryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder..
        /// </summary>
        public static string SelectAFolderMessage {
            get {
                return ResourceManager.GetString("SelectAFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not rated yet..
        /// </summary>
        public static string UnratedDescription {
            get {
                return ResourceManager.GetString("UnratedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attractive collectible with a moderate defect or an accumulation of small defects..
        /// </summary>
        public static string VeryFineDescription {
            get {
                return ResourceManager.GetString("VeryFineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An above-average collectible with a moderate defect or an accumulation of small defects..
        /// </summary>
        public static string VeryFineMinusDescription {
            get {
                return ResourceManager.GetString("VeryFineMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A very well-preserved collectible with good eye appeal. There will be a number of minor handling and/or manufacturing defects..
        /// </summary>
        public static string VeryFineNearMintDescription {
            get {
                return ResourceManager.GetString("VeryFineNearMintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attractive collectible with a moderate defect or a number of small defects..
        /// </summary>
        public static string VeryFinePlusDescription {
            get {
                return ResourceManager.GetString("VeryFinePlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A below-average collectible with multiple moderate defects..
        /// </summary>
        public static string VeryGoodDescription {
            get {
                return ResourceManager.GetString("VeryGoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An average collectible with several moderate defects..
        /// </summary>
        public static string VeryGoodFineDescription {
            get {
                return ResourceManager.GetString("VeryGoodFineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A below-average collectible with several major defects or an accumulation of multiple moderate defects..
        /// </summary>
        public static string VeryGoodMinusDescription {
            get {
                return ResourceManager.GetString("VeryGoodMinusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A slightly below-average collectible with multiple moderate defects..
        /// </summary>
        public static string VeryGoodPlusDescription {
            get {
                return ResourceManager.GetString("VeryGoodPlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
